import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar.jsx'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div style={{ maxWidth:'500px',
                      padding:'10px 20px',
                      // color:'white',
                      margin:'0 auto',
                      // padding:'10px 20px',
                      // background:'black'
                      }}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
